### ISSUE TITLE
Generate infrastructure model

### ISSUE THREAD

**Issue by mkeskells** [rorygraves/ScalaClean#14]
- [x] basic model to store code interrelationship
- [x] support for multiple classpaths, e.g. modules
- [x] incoming and outgoing references

support for class inhertance based queries - does a class implement `App`
- [x] direct inheritance child -> parent
- [x] direct inheritance parent -> child
- [x] indirect inheritance child -> parent
- [x] indirect inheritance parent -> child

support for method inheritance
- [x] child -> parent
- [x] parent -> child
- [x] direct 
- [x] transitive
- [x] var child up to (field, + 2 methods)
- [x] val child up to (field, + 1 method)
- [x] object

**Comment by rorygraves** [comment]
Complee
